name: mercantis_core_mono
description: Mercantis Core Flutter monorepo root.
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/mercantis_core
  - packages/mercantis_core_ui
  - app
